// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace yedim.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20241217093221_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Meyve"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Sebze"
                        });
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Price = 18000m,
                            ProductName = "computer"
                        },
                        new
                        {
                            ProductId = 2,
                            Price = 20000m,
                            ProductName = "klavye"
                        },
                        new
                        {
                            ProductId = 3,
                            Price = 30000m,
                            ProductName = "fare"
                        },
                        new
                        {
                            ProductId = 4,
                            Price = 50000m,
                            ProductName = "ekran"
                        },
                        new
                        {
                            ProductId = 5,
                            Price = 17000m,
                            ProductName = "deck"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
